// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
let supabaseClient: ReturnType<typeof createClient<Database>> | null = null;
let initializationError: Error | null = null;

try {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missingVars = [];
    if (!SUPABASE_URL) missingVars.push('VITE_SUPABASE_URL');
    if (!SUPABASE_PUBLISHABLE_KEY) missingVars.push('VITE_SUPABASE_PUBLISHABLE_KEY');

    const errorMessage = `Missing required environment variables: ${missingVars.join(', ')}. Please check your .env file.`;
    console.error('❌ Missing Supabase environment variables:', missingVars.join(', '));
    console.error('📝 Please create a .env file in the project root with:');
    console.error('   VITE_SUPABASE_URL=your_supabase_url');
    console.error('   VITE_SUPABASE_PUBLISHABLE_KEY=your_supabase_anon_key');

    initializationError = new Error(errorMessage);

    // Create a placeholder client to prevent import errors
    // This allows the ErrorBoundary to catch and display the error
    supabaseClient = createClient<Database>(
      'https://placeholder.supabase.co',
      'placeholder-key',
      {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      }
    );
  } else {
    console.log('✅ Supabase client initialized with URL:', SUPABASE_URL.substring(0, 30) + '...');

    try {
      supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
          detectSessionInUrl: true,
        }
      });
      console.log('✅ Supabase createClient successful');
    } catch (err) {
      console.error('❌ Error during createClient:', err);
      throw err;
    }
  }
} catch (error) {
  console.error('❌ Failed to initialize Supabase client:', error);
  initializationError = error instanceof Error ? error : new Error('Unknown error initializing Supabase');

  // Create a placeholder client to prevent import errors
  supabaseClient = createClient<Database>(
    'https://placeholder.supabase.co',
    'placeholder-key',
    {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    }
  );
}

// Export the supabase client directly
// Note: If initialization failed, this will be a placeholder client
// The App component checks environment variables and shows ConfigError if missing
export const supabase = supabaseClient!;

// Export error check function and initialization error
export const checkSupabaseConfig = () => {
  return !initializationError;
};

export const getInitializationError = () => {
  return initializationError;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";